import {useEffect, useState} from 'react';
import type {Card, HistoryPage, Kind, Learning, Library, Topic} from '../types';
import type {LocalReviewStore} from '../api';
import M from '../model/learning-model.js';
import {dayKey,displayTime,now,timeZone} from '../model/time.js';
import {errorText,kindNames,ratingText} from '../components';

const statuses:Record<string,string>={overdue:'已逾期',due:'现在可复习',scheduled:'等待下次复习',practice:'自由练习',undone:'记录已撤销'};
type Props={data:Learning;library:Library;topic:Topic;params:URLSearchParams;update:(values:Record<string,string>)=>void;start:(uid:string,kind?:Kind,practice?:boolean)=>void;history:(uid:string)=>void};
export default function LearningCenter({data,library,topic,params,update,start,history}:Props){
  const m=M.build(data,library,topic.id,now()),today=data.days.at(-1)!;
  const tab=['overview','records','board'].includes(params.get('tab')||'')?params.get('tab'):'overview';
  const records=(values:Record<string,string>={})=>update({tab:'records',query:'',filterTopic:'',status:'',from:'',to:'',sort:'last',page:'1',...values});
  const startPlanned=(c:Card)=>start(c.uid,data.state.records[c.uid]?.phase||'main',false);
  const fields={query:params.get('query')||'',topic:params.get('filterTopic')||'',status:params.get('status')||'',from:params.get('from')||'',to:params.get('to')||'',sort:params.get('sort')||'last'};
  const rows=M.filterRows(m.rows,fields),pages=Math.max(1,Math.ceil(rows.length/20)),page=Math.min(pages,Math.max(1,Number(params.get('page'))||1));
  return <><div className="center-tabs" aria-label="学习中心页面">{[['overview','学习总览'],['records','刷题记录'],['board','复习看板']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>update({tab:key})}>{label}</button>)}</div>
    {tab==='overview'&&<>
      <div className="overview-welcome"><div><p className="eyebrow">YOUR LEARNING, AT A GLANCE</p><h3>每一次回忆，都看得见。</h3><p className="muted">{dayKey(now())} · {M.modeLabel(data.settings.dailyNewLimit)} · 共享学习时区 {timeZone()}</p></div><button className="primary" onClick={()=>update({tab:'board'})}>去复习看板 →</button></div>
      <div className="metric-grid"><button className="metric" onClick={()=>records()}><span>累计刷过</span><strong>{m.learned}<small>题</small></strong><p>{m.submissions} 次有效提交</p></button><button className="metric" onClick={()=>records({from:today.date,to:today.date})}><span>今天已完成</span><strong>{today.total}<small>题</small></strong><p>新题 {today.new} · 复习 {today.review} · 自由练习 {today.practice}</p></button><button className="metric" onClick={()=>update({tab:'board'})}><span>当前待复习</span><strong>{m.due.length}<small>题</small></strong><p>{m.overdue} 题已逾期 · 全专题</p></button><button className="metric" onClick={()=>document.getElementById('topic-progress')?.scrollIntoView()}><span>已开始的专题</span><strong>{m.topics.filter(t=>t.learned).length}<small>/ {library.topics.length}</small></strong><p>按题目去重统计</p></button></div>
      <div className="overview-grid"><section className="center-card"><h3>最近 7 天</h3><div className="week-chart">{data.days.map(d=><button key={d.date} className="day-column" aria-label={`查看 ${d.date} 的 ${d.total} 道题`} onClick={()=>records({from:d.date,to:d.date})}><span className="day-value">{d.total}</span><span className="bar-space"><span className="day-bar" style={{height:`${Math.max(3,d.total/Math.max(1,...data.days.map(x=>x.total))*100)}%`,opacity:d.total?1:.2}}/></span><span>{d.date===dayKey(now())?'今天':d.date.slice(5)}</span></button>)}</div><p className="fine-print">同题一天计 1 题；重复提交另计次数。撤销不计入统计，旧版累计记录不补入每日图表。</p></section>
      <section className="center-card"><div className="panel-heading"><h3>最近提交</h3><button className="text-button" onClick={()=>records()}>查看全部</button></div>{data.recent.length?data.recent.map(e=><button className="recent-row" key={e.id} onClick={()=>history(e.uid)}><span><strong>{m.rows.find(r=>r.uid===e.uid)?.card.title||e.uid}</strong><small>{displayTime(e.at)}</small></span><span className="pill">{e.practice?'自由练习':kindNames[e.kind]}</span></button>):<p className="center-empty">完成一次自评，提交时间就会出现在这里。</p>}</section></div>
      <section className="center-card" id="topic-progress"><h3>专题进度</h3><div className="topic-progress-grid">{m.topics.map(t=><button key={t.id} className="topic-progress" onClick={()=>records({filterTopic:t.id})}><span>{t.number} · {t.title}<strong>{t.learned} / {t.cards.length}</strong></span><span className="mini-track"><span style={{width:`${t.learned/t.cards.length*100}%`}}/></span></button>)}</div></section>
    </>}
    {tab==='records'&&<><p className="muted">每题一行；自评成功保存后计入提交。共享时区：{timeZone()}。</p><div className="record-filters"><label className="filter-search">查找题目<input type="search" value={fields.query} onChange={e=>update({query:e.target.value,page:'1'})}/></label><label>专题<select value={fields.topic} onChange={e=>update({filterTopic:e.target.value,page:'1'})}><option value="">所有专题</option>{library.topics.map(t=><option value={t.id} key={t.id}>{t.number} · {t.title}</option>)}</select></label><label>复习状态<select value={fields.status} onChange={e=>update({status:e.target.value,page:'1'})}><option value="">所有状态</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{[['from','提交开始日期'],['to','提交结束日期']].map(([key,label])=><label key={key}>{label}<input type="date" value={params.get(key)||''} onChange={e=>update({[key]:e.target.value,page:'1'})}/></label>)}<label>排序<select value={fields.sort} onChange={e=>update({sort:e.target.value})}>{[['last','最近提交优先'],['first','最近首次学习'],['count','提交次数最多'],['due','复习日期最早']].map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><button className="text-button" onClick={()=>records()}>清除筛选</button></div>
      <p role="status" className="muted">{fields.from&&fields.to&&fields.from>fields.to?'开始日期不能晚于结束日期。':`共 ${rows.length} 道题 · 第 ${page} / ${pages} 页`}</p>
      {rows.length?<div className="table-scroll" tabIndex={0} aria-label="刷题记录表格"><table className="records-table"><thead><tr>{['题目','首次学习','最近提交','有效提交','复习状态','操作'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.slice((page-1)*20,page*20).map(r=><tr key={r.uid}><td><button className="record-title" onClick={()=>history(r.uid)}>{r.card.id} · {r.card.title}</button><small>{r.card.topicTitle}</small></td><td>{displayTime(r.firstAt)}</td><td>{displayTime(r.lastAt)}</td><td>{r.eventCount} 次{r.legacyCount>0&&<small>另有旧版累计 {r.legacyCount} 次</small>}</td><td><span className={`status-tag ${r.status}`}>{statuses[r.status]}</span>{r.record&&<small>{displayTime(r.record.due)}</small>}</td><td><button className="text-button" onClick={()=>history(r.uid)}>时间线</button>{r.card.topicId&&<button className="text-button" onClick={()=>start(r.uid,undefined,true)}>现在练习</button>}</td></tr>)}</tbody></table></div>:<p className="center-empty">没有匹配的题目。可以清除筛选，或先完成一次自评。</p>}
      {pages>1&&<div className="record-pages"><button className="secondary" disabled={page===1} onClick={()=>update({page:String(page-1)})}>上一页</button><span>{page} / {pages}</span><button className="secondary" disabled={page===pages} onClick={()=>update({page:String(page+1)})}>下一页</button></div>}
    </>}
    {tab==='board'&&<><div className="board-intro"><div><h3>今天，从这里开始。</h3><p className="muted">{M.modeLabel(data.settings.dailyNewLimit)} · 今天已引入 {m.introduced} 道新题，还可引入 {m.remaining} 道。</p></div><button className="primary" disabled={!m.due.length&&!m.fresh.length} onClick={()=>startPlanned(m.due[0]||m.fresh[0])}>开始下一题 →</button></div><p className="fine-print">到期旧题覆盖全部专题；新题从“{topic.title}”开始。切换模式不重置当天额度。</p><div className="review-board">{(['due','fresh','done'] as const).map((type,index)=>{const cards:Card[]=type==='done'?m.done.flatMap(e=>e.card?[e.card]:[]):m[type];return <section key={type} className="board-column"><div className="column-heading"><h3>{['待复习','今日新题','今日已完成'][index]}</h3><span>{cards.length}</span></div>{cards.map(c=>{const r=data.state.records[c.uid],event=data.today.find(e=>e.uid===c.uid);return <article className="board-card" key={c.uid}><span className="board-meta">LC {c.id}</span><h4>{c.title}</h4>{type==='done'&&event?<p className="muted">提交于 {displayTime(event.at,true)} · {ratingText(event.ratings)}</p>:r&&<p className="muted">到期 {displayTime(r.due)}</p>}{data.state.notes[c.uid]?.text&&<p className="board-note">卡点：{data.state.notes[c.uid].text}</p>}<div className="board-actions"><button className="text-button" onClick={()=>type==='done'?history(c.uid):startPlanned(c)}>{type==='done'?'查看提交':type==='fresh'?'开始学习':'开始复习'} →</button></div></article>;})}{!cards.length&&<p className="column-empty">{type==='due'?'现在没有到期题。':type==='fresh'?m.remaining?'本专题没有待学新题，可切换专题。':'今天的新题额度已用完。':'保存自评后，留下今天的记录。'}</p>}</section>;})}</div><p className="fine-print">“已完成”表示今天提交过，不代表掌握。没想起的题到期后会再次进入待复习。</p></>}
  </>;
}

export function Timeline({uid,store,data,onUndo,onStart}:{uid:string;store:LocalReviewStore;data:Learning;onUndo:(id:string)=>Promise<void>;onStart:()=>void}){
  const [history,setHistory]=useState<HistoryPage>({events:[],nextCursor:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void store.request<HistoryPage>(`/api/history?uid=${encodeURIComponent(uid)}`).then(h=>{if(active){setHistory(h);setError('');}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[uid,data.revision,store]);
  const problem=data.problems.find(p=>p.uid===uid);
  async function more(){setBusy(true);try{const h=await store.request<HistoryPage>(`/api/history?uid=${encodeURIComponent(uid)}&before=${history.nextCursor}`);setHistory(old=>({events:[...old.events,...h.events],nextCursor:h.nextCursor}));setError('');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <><div className="detail-summary"><span>{problem?.eventCount||0} 次有效提交 · {timeZone()}</span><button className="primary" onClick={onStart}>现在练习</button></div>{!!problem?.legacyCount&&<p className="legacy-note">另有旧版累计 {problem.legacyCount} 次；没有逐次事件，不编造历史提交。</p>}{error&&<p className="warning" role="alert">{error}</p>}{history.events.map(e=><article className={`timeline-event ${e.undone?'is-undone':''}`} key={e.id}><div className="timeline-meta"><time dateTime={new Date(e.at).toISOString()}>{displayTime(e.at)}</time><span>{e.undone?'已撤销':e.practice?'自由练习':'计划复习'}</span></div><h3>{kindNames[e.kind]}</h3><p>{ratingText(e.ratings)}{e.usedHelp?' · 使用过提示或概念':''}</p><p>{e.due?`当次安排下次复习：${displayTime(e.due)}`:'本次练习未改变复习日期'}</p>{e.canUndo&&<button className="text-button" disabled={busy} onClick={()=>{setBusy(true);void onUndo(e.id).finally(()=>setBusy(false));}}>撤销这次记录</button>}</article>)}{!history.events.length&&!error&&<p className="center-empty">没有可展开的逐次提交。</p>}{history.nextCursor&&<button className="secondary" disabled={busy} onClick={()=>void more()}>加载更早提交</button>}</>;
}
