import {useEffect,useState} from 'react';
import type {DatabaseStatus,Kind,Library,Snapshot,Topic} from '../types';
import type {LocalReviewStore} from '../api';
import {displayTime,timeZone} from '../model/time.js';
import {Modes,download,errorText,scores,skillNames} from '../components';

export function MemoryMap({library,topic,snapshot,search,onSearch,start,connections}:{library:Library;topic:Topic;snapshot:Snapshot;search:string;onSearch:(value:string)=>void;start:(uid:string,kind:Kind,practice:boolean)=>void;connections:(uid:string)=>void}){
  const terms=search.trim().toLowerCase().split(/\s+/).filter(Boolean),scope=terms.length?library.topics:[topic];
  const groups=scope.flatMap(t=>t.groups.map(g=>({topic:t,group:g,cards:t.cards.filter(c=>c.group===g.id&&terms.every(term=>`${c.id} ${c.uid} ${c.title} ${c.prompt} ${c.mnemonic} ${c.recognition} ${c.invariant} ${t.title}`.toLowerCase().includes(term)))}))).filter(g=>g.cards.length);
  return <><p className="section-intro">{terms.length?'跨专题比较题目条件，再理解方法什么时候相同、什么时候改变。':topic.connectionRule}</p><div className="map-search"><label>在所有专题中找题或思路<input type="search" value={search} onChange={e=>onSearch(e.target.value)} placeholder="例如：238、冷却、容量、环入口"/></label><p className="muted" role="status">{groups.reduce((n,g)=>n+g.cards.length,0)} 道匹配题目{terms.length?' · 已搜索全部 177 道题':''}</p></div>{groups.map(({topic:t,group:g,cards})=><section className="map-group" key={`${t.id}:${g.id}`}><h3>{terms.length?`${t.title} / `:''}{g.title}</h3><p>{g.description}</p><div className="map-list">{cards.map(c=><article className="map-card" key={c.uid}><div className="map-meta"><span>LC {c.id} · {c.level}</span><span>{snapshot.state.records[c.uid]?displayTime(snapshot.state.records[c.uid].due):'未开始'}</span></div><strong>{c.title}</strong><p>{c.mnemonic}</p><div className="skill-status">{(Object.keys(skillNames) as (keyof typeof skillNames)[]).map(k=>{const skill=snapshot.state.skills[c.uid]?.[k];return <span key={k} className={`skill-${skill?.value??'unrated'}`}>{skillNames[k]}：{skill?scores[skill.value]:'未评'}</span>;})}</div>{snapshot.state.notes[c.uid]?.text&&<p className="map-mistake">卡点：{snapshot.state.notes[c.uid].text}</p>}<div className="map-actions"><button className="text-button" onClick={()=>start(c.uid,'main',true)}>回忆</button><button className="text-button" onClick={()=>start(c.uid,'followup',true)}>追问</button><button className="text-button" onClick={()=>start(c.uid,'code',true)}>{snapshot.drafts[`${c.uid}:code`]?.text?'继续默写':'默写'}</button><button className="text-button" onClick={()=>connections(c.uid)} aria-label={`查看 ${c.title} 的关联题`}>关联 · {c.related.length}</button></div></article>)}</div></section>)}{!groups.length&&<p className="empty-state">没有匹配的题目。试试题号、题名或更短的线索。</p>}</>;
}

export function DataSettings({store,snapshot,onMode,onRestore,onExport,onImport,notice}:{store:LocalReviewStore;snapshot:Snapshot;onMode:(n:number)=>void;onRestore:(name:string)=>void;onExport:()=>void;onImport:()=>void;notice:(text:string)=>void}){
  const [status,setStatus]=useState<DatabaseStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void store.request<DatabaseStatus>('/api/status').then(s=>{if(active){setStatus(s);setError('');}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[snapshot.revision,snapshot.databaseId,store]);
  async function backup(){setBusy(true);try{setStatus(await store.request<DatabaseStatus>('/api/backup',{method:'POST',body:'{}'}));notice('已创建完整 SQLite 备份并检查完整性。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <div className="guide-card"><h3>共享进度与学习节奏</h3><Modes limit={snapshot.settings.dailyNewLimit} onMode={onMode}/><p>所有参与者共享进度、设置、卡点、草稿与历史。每人均可导入、撤销和恢复；这里没有个人私有笔记。</p><p>共享学习时区：<strong>{timeZone()}</strong>。切换模式不重置今天已用的新题额度。</p><h3>保存与导入导出</h3><div className="practice-actions"><button className="secondary" onClick={onExport}>{store.queue.length||store.blocked?'导出待保存内容':'导出已提交记录 JSON'}</button><button className="secondary" onClick={onImport}>导入 JSON</button><button className="text-button" onClick={()=>{try{const raw=store.legacyRaw();if(!raw)throw Error('此浏览器没有旧版进度。');download(raw,'拾忆-旧浏览器进度.json');}catch(e){notice(errorText(e));}}}>导出旧浏览器原文</button></div><p className="fine-print">JSON 用于携带和合并记录，不是精确回滚副本。待保存文件保留原请求 ID 和数据库标识；来自恢复前或未知数据库的操作必须单独确认。</p><h3>数据库状态</h3>{error&&<p className="warning" role="alert">{error}</p>}{status?<><p>已开始 {status.startedCount} 题 · {status.reviewCount} 次有效提交</p><p className="data-path">{status.databasePath}</p><p className="data-path">备份目录：{status.backupPath}</p>{status.backupError&&<p className="warning">{status.backupError}</p>}</>:<p>正在读取数据库状态…</p>}<h3>完整备份与恢复</h3><p>启动、正常退出、写入期间至少间隔 15 分钟，以及导入和恢复前创建备份；最多保留 30 份。准确回到过去某个状态应使用这些 SQLite 备份。</p><button className="primary" disabled={busy||!!store.queue.length} onClick={()=>void backup()}>现在创建备份</button>{!!store.queue.length&&<p className="warning">请先处理待保存内容，再创建备份或恢复。</p>}{status?.backups.map(b=><div className="backup-item" key={b.name}><div><strong>{displayTime(b.at)}</strong><span>{b.name}</span><span>{Math.ceil(b.bytes/1024)} KB</span></div><button className="secondary" disabled={!!store.queue.length} onClick={()=>onRestore(b.name)}>恢复此备份</button></div>)}</div>;
}
export function Guide(){return <div className="guide-card"><ol className="ritual"><li><strong>3 分钟 · 回忆旧题</strong><p>先说题型、关键变量和边界。想不出，停一下再看提示。</p></li><li><strong>休闲模式 · 最多 3 道新题</strong><p>记一句思路，并解释为什么成立。疯狂模式每天最多 20 道；额度在专题与设备间共享。</p></li><li><strong>7 分钟 · 默写一道</strong><p>合上参考，在默写区写完整代码；手推普通与边界输入，再核对。这里不运行或判题。</p></li></ol><div className="callout"><strong>每道题只问三个问题</strong><p>用什么办法？关键变量一直表示什么？哪个边界最容易错？</p></div><h3>诚实地评价刚才的回忆</h3><p>认出方法、讲清原因、独立写出分别评分。没想起：10 分钟后再试；需要帮助：1 天后；独立完成：1、3、7、14、30 天。主卡两项取较弱的一项；核对前用过提示或概念，最高为“需要帮助”。</p><p>成功复习后主卡与追问交替；自由练习与代码默写更新能力和历史，不改变计划复习日期。固定间隔不是自适应排程。</p><h3>比较关联题</h3><p>记忆地图按关键决策分组，搜索覆盖全部专题。先比较条件，再解释方法为什么相同或不同。原题解保留完整代码和来源。</p><h3>共享保存与断线</h3><p>只有收到数据库确认才显示已保存。断线请求暂存在当前浏览器，并用同一编号重试。不要清理有待保存内容的浏览器；可以先导出。无法暂存时保持页面打开。</p><p>新端口、localhost 与 127.0.0.1、Tailscale HTTPS 是不同浏览器来源。换入口前先处理或导出旧入口的队列，保留旧浏览器原文。恢复后旧请求需要明确确认；有草稿冲突时比较双方内容。</p><h3>使用纸笔也能练</h3><p>左边写题名，右边写一句思路和一个坑，遮住右边复述。按第 1、3、7、14 天回来抽查。</p><p className="muted">方法依据：<a href="https://www.learningscientists.org/faq" target="_blank" rel="noreferrer">主动回忆与间隔练习</a>。题解来自本仓库的公开内容。</p></div>;}
