import {useEffect, useRef} from 'react';
import type {Attempt, Card, Kind, Library, Skill, Snapshot, Topic} from '../types';
import type {LocalReviewStore} from '../api';
import {DraftInput,kindNames,skillNames,scores} from '../components';
import {schedule} from '../model/review-engine.js';
import {displayTime,now} from '../model/time.js';

export function Answer({card:c}:{card:Card}){
  return <><p className="eyebrow">一句话记住</p><p className="mnemonic">{c.mnemonic}</p><p className="why">{c.why}</p><div className="callout"><strong>关键变量一直表示什么</strong><p>{c.invariant}</p></div><h4>怎么一步步写出来</h4><ol className="steps">{c.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><div className="trap"><strong>容易错的地方</strong><p>{c.trap}</p></div><p className="complexity">{c.complexity}</p><details className="code-details"><summary>{c.traceLabel||'手推一遍例子'}</summary><pre className="trace">{c.trace}</pre></details></>;
}
export default function StudyCard({attempt,card:c,topic,library,snapshot,store,busy,change,submit,practice,concepts,related,onError}:{attempt:Attempt;card:Card;topic:Topic;library:Library;snapshot:Snapshot;store:LocalReviewStore;busy:boolean;change:(patch:Partial<Attempt>)=>void;submit:()=>void;practice:(kind:Kind)=>void;concepts:()=>void;related:(uid:string)=>void;onError:(message:string)=>void}){
  const {kind,revealed,hintLevel,usedHelp,ratings}=attempt;
  const keys:Skill[]=kind==='main'?['recognize','explain']:kind==='code'?['implement']:['explain'];
  const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{if(revealed)heading.current?.focus({preventScroll:true});},[revealed]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.isComposing||event.repeat||event.ctrlKey||event.metaKey||event.altKey||document.querySelector('dialog[open]')||(event.target as HTMLElement)?.closest('input,textarea,button,select,summary,a,[contenteditable=true]'))return;if(event.code==='Space'&&!revealed){event.preventDefault();change({revealed:true});return;}if(!revealed||busy)return;const score=['Digit1','Digit2','Digit3'].indexOf(event.code);if(score>=0){const blank=keys.find(k=>ratings[k]===undefined);if(blank&&!(usedHelp&&score===2)){event.preventDefault();change({ratings:{...ratings,[blank]:score}});}return;}if(event.code==='Enter'&&keys.every(k=>ratings[k]!==undefined)){event.preventDefault();submit();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[revealed,change,busy,keys,ratings,usedHelp,submit]);
  const values=keys.flatMap(key=>ratings[key]===undefined?[]:[ratings[key]!]);
  const preview=values.length?schedule(snapshot.state.records[c.uid],Math.min(...values,usedHelp?1:2),now()):null;
  const code=<>{c.codeNote&&<p className="muted">{c.codeNote}</p>}<pre className="solution-code"><code>{c.code}</code></pre></>;
  return <article className="study-card" data-testid="study-card"><div className="card-body"><div className="card-meta"><span>LEETCODE {c.id}</span><span className="pill">{c.level}</span><span>{kindNames[kind]}</span></div><h3>{c.title}</h3><p className="problem">{kind==='followup'?c.followup.prompt:c.prompt}</p>{kind==='followup'?<details><summary>题目背景</summary><p>{c.prompt}</p></details>:<pre className="example">{c.example}</pre>}
    {snapshot.state.notes[c.uid]?.text&&<p className="mistake-prompt">这次也检查一下：{snapshot.state.notes[c.uid].text}</p>}
    <p className="recall-title">{kind==='code'?'合上参考，写完整函数，再手推一个边界输入。':kind==='followup'?'先解释，再用一个例子验证。':'先花 30 秒，在脑海里回答'}</p>{kind==='main'&&<ol className="recall-list"><li>用什么办法？</li><li>关键变量是什么？</li><li>为什么这样做？</li></ol>}
    <details className="scratch" open={kind==='code'||undefined}><summary>{kind==='code'?'Python 默写区':'写下我的思路（可选）'}</summary><DraftInput store={store} snapshot={snapshot} uid={c.uid} kind={kind} label={kind==='code'?'Python 默写代码':'思路草稿'} readOnly={revealed} onError={onError}/><p className="fine-print">草稿由所有参与者共享并自动保存。这里不执行代码。</p></details>
    {!!hintLevel&&<div className="hint-box">{[c.hint,`关键观察：${c.recognition}`,c.steps.join('\n')].slice(0,hintLevel).map((hint,i)=><p key={i}><strong>提示 {i+1}</strong> · {hint}</p>)}</div>}
    {!revealed&&<div className="help-actions"><button className="secondary" disabled={hintLevel>=3} onClick={()=>change({hintLevel:hintLevel+1,usedHelp:true})}>{hintLevel?`再给一层提示 · ${hintLevel}/3`:'给我一点提示'}</button><button className="text-button" onClick={()=>{change({usedHelp:true});concepts();}}>补一个相关概念</button></div>}
    </div>{!revealed&&<div className="card-actions"><button className="primary" onClick={()=>change({revealed:true})}>{kind==='code'?'写完了，对照代码':'我想好了，核对答案'} <span className="key">Space</span></button><span className="muted">先尝试，再展开</span></div>}
    {revealed&&<><div className="answer"><h4 ref={heading} tabIndex={-1} className="answer-heading">{kind==='code'?'参考代码':'核对刚才的回答'}</h4>{kind==='main'?<Answer card={c}/>:kind==='code'?code:<><p className="follow-answer">{c.followup.answer}</p><details><summary>完整思路</summary><Answer card={c}/></details></>}</div>
      <form className="rating-area" onSubmit={e=>{e.preventDefault();if(keys.every(key=>ratings[key]!==undefined))submit();}}><p>只评价合上答案时的表现。{usedHelp?'本次用过提示或概念，最高记录为“需要帮助”。':''}<span className="key">1/2/3 评分 · Enter 保存</span></p>{keys.map(key=><fieldset className="skill-rating" key={key}><legend>{skillNames[key]}</legend><div className="rating-options">{scores.map((label,value)=><label key={value}><input type="radio" name={key} required checked={ratings[key]===value} disabled={busy||(usedHelp&&value===2)} onChange={()=>change({ratings:{...ratings,[key]:value}})}/><span>{label}</span></label>)}</div></fieldset>)}
      <DraftInput store={store} snapshot={snapshot} uid={c.uid} type="note" label="下次最想检查的一个卡点" onError={onError}/><p className="fine-print">卡点自动保存，下次会再次提醒。</p><div className="submit-row"><button className="primary" type="submit" disabled={busy}>{busy?'正在保存…':attempt.practice?'保存自评，结束练习':'保存自评，下一题'}</button><span className="muted">{attempt.practice||kind==='code'?'自由练习不改复习日期':preview?`下次：${preview.label}（${displayTime(preview.due)}）`:'选择后显示下次复习时间'}</span></div></form>
      <div className="answer extras">{kind!=='code'&&<details className="code-details"><summary>查看 Python 参考代码</summary>{code}</details>}<div className="practice-actions">{kind!=='followup'&&<button className="text-button" disabled={busy} onClick={()=>practice('followup')}>换个问题自测</button>}{kind!=='code'&&<button className="text-button" disabled={busy} onClick={()=>practice('code')}>合上答案，默写这题</button>}</div><details className="code-details"><summary>相关概念与容易混淆的题</summary><h4>看到什么，想到这个方法</h4><p>{c.recognition}</p><button className="concept-chip" onClick={concepts}>{topic.concepts.filter(x=>c.prerequisites.includes(x.id)).map(x=>x.title).join(' · ')}</button><div className="related-list">{c.related.map(r=><div key={r.id}><span className="relation-kind">{r.kind||'思路联系'}</span><strong>{r.id} · {library.topics.flatMap(t=>t.cards).find(x=>x.id===r.id)?.title}</strong><p>{r.why}</p><button className="text-button" onClick={()=>related(`lc-${r.id}`)}>打开对比题</button></div>)}</div></details><div className="links"><a href={c.noteUrl} target="_blank" rel="noopener">本地原题解</a><a href={c.url} target="_blank" rel="noreferrer">题目页面</a></div></div>
    </>}
  </article>;
}
